In [10]:
import numpy as np
import pandas as pd

# List of comments (100 positive and 100 negative)
comments = [
    # Positive comments (1)
    "I loved the movie, the acting was incredible.",
    "The plot was captivating from start to finish.",
    "The cinematography was beautiful.",
    "The characters were well-developed and interesting.",
    "I was on the edge of my seat the entire time.",
    "One of the best films I've seen in years.",
    "The director did a fantastic job.",
    "I can't wait to watch it again.",
    "The special effects were top-notch.",
    "The soundtrack added so much to the film.",
    "It was a thrilling experience.",
    "The performances were amazing.",
    "An outstanding piece of work.",
    "The story was so touching.",
    "Everything about the film was perfect.",
    "I was completely immersed in the world of the movie.",
    "The action scenes were breathtaking.",
    "I enjoyed every moment.",
    "The humor was spot on.",
    "A must-see for any movie lover.",
    "A heartwarming story that stays with you.",
    "I highly recommend this film to everyone.",
    "It was an emotional rollercoaster.",
    "A visually stunning masterpiece.",
    "I couldn't take my eyes off the screen.",
    "The ending was so satisfying.",
    "This film deserves all the praise it's getting.",
    "One of the most entertaining films this year.",
    "The actors delivered stellar performances.",
    "It was a true cinematic experience.",
    "The script was well-written and engaging.",
    "A powerful film that left a lasting impression.",
    "I was completely blown away by the movie.",
    "The emotional depth of the story was amazing.",
    "The film was very thought-provoking.",
    "The pacing was perfect, not a dull moment.",
    "The director's vision was executed perfectly.",
    "The visual effects were outstanding.",
    "A brilliant film, highly recommended.",
    "An unforgettable experience.",
    "The chemistry between the leads was fantastic.",
    "The movie exceeded all my expectations.",
    "I was thoroughly entertained.",
    "The storytelling was superb.",
    "I felt a deep connection to the characters.",
    "It was a beautifully crafted film.",
    "The film was so gripping.",
    "A great blend of action and emotion.",
    "It was a joy to watch from beginning to end.",
    "The movie was well worth the time.",
    "It kept me engaged throughout.",
    "The dialogue was sharp and witty.",
    "I would definitely watch this again.",
    "The film had a lot of heart.",
    "The cast was phenomenal.",
    "I was moved by the story.",
    "A great mix of drama and comedy.",
    "A true work of art.",
    "The film was both entertaining and meaningful.",
    "It was beautifully acted and directed.",
    "I walked out of the theater feeling inspired.",
    "It was pure cinematic magic.",
    "A refreshing and original movie.",
    "The film exceeded all my expectations.",
    "The story had me hooked from the start.",
    "It was one of the best films I've ever seen.",
    "The performances were mesmerizing.",
    "I absolutely adored this movie.",
    "The action was fast-paced and exciting.",
    "The movie was an emotional journey.",
    "A stunning achievement in filmmaking.",
    "A beautifully told story.",
    "It was a joy to watch.",
    "I found the film very uplifting.",
    "The movie was deeply moving.",
    "A fantastic film with a strong message.",
    "I was thoroughly impressed.",
    "It was a heartfelt and emotional film.",
    "The film was both funny and poignant.",
    "An inspiring story well-told.",
    "I was completely engaged throughout.",
    "The cinematography was simply breathtaking.",
    "I was blown away by the performances.",
    "The movie was full of energy and life.",
    "A brilliant and captivating film.",
    "It was an unforgettable experience.",
    "The acting was exceptional.",
    "The movie had me in tears.",
    "A masterpiece of modern cinema.",
    "It was a thrilling and emotional film.",
    "I loved every second of it.",
    "The film was a visual feast.",
    "I was deeply touched by the story.",
    "The movie was a rollercoaster of emotions.",
    "It was a refreshing and unique take on the genre.",
    "The story was beautifully crafted.",
    "It was a powerful and moving film.",
    "The film had a lasting impact on me.",
    "A well-crafted and engaging film.",
    
    # Negative comments (0)
    "The movie was a total disappointment.",
    "I found the plot to be predictable and boring.",
    "The acting was subpar and unconvincing.",
    "The film felt way too long and dragged on.",
    "I didn't care about any of the characters.",
    "The ending was confusing and unsatisfying.",
    "The pacing was slow and tedious.",
    "The humor was forced and fell flat.",
    "The story lacked depth and originality.",
    "It was one of the worst movies I've seen.",
    "I regret wasting my time on this film.",
    "The dialogue was cringeworthy.",
    "I couldn't connect with the story at all.",
    "The special effects were laughably bad.",
    "The film was painfully dull.",
    "The characters were one-dimensional and boring.",
    "It was an overall forgettable experience.",
    "The direction was sloppy and unfocused.",
    "The movie had no redeeming qualities.",
    "The plot was a complete mess.",
    "The performances were uninspired.",
    "The movie felt like a waste of potential.",
    "I didn't enjoy the film at all.",
    "It was a huge letdown.",
    "The story didn't make any sense.",
    "The action scenes were poorly executed.",
    "It was a boring and uninspired film.",
    "I fell asleep halfway through.",
    "The film had no emotional impact.",
    "The movie tried too hard to be funny.",
    "It was a terrible movie from start to finish.",
    "The characters were annoying and unlikeable.",
    "The story was all over the place.",
    "The acting was wooden and stiff.",
    "I couldn't wait for the movie to end.",
    "The plot holes were impossible to ignore.",
    "The movie was completely forgettable.",
    "The direction was amateurish.",
    "It was an absolute disaster of a film.",
    "The movie had no heart.",
    "It was painfully slow and boring.",
    "I wouldn't recommend this movie to anyone.",
    "It was a waste of time and money.",
    "The movie was completely unoriginal.",
    "The writing was lazy and uninspired.",
    "The characters were poorly written.",
    "It was one of the worst films I've ever seen.",
    "The movie lacked any real substance.",
    "It was a complete train wreck.",
    "The acting was laughably bad.",
    "The plot was full of cliches.",
    "The film was an absolute mess.",
    "It was a waste of two hours.",
    "I found the movie incredibly boring.",
    "The dialogue was awful.",
    "The plot was incoherent and confusing.",
    "The film was poorly paced and edited.",
    "It was a painfully unfunny comedy.",
    "The movie felt cheap and rushed.",
    "The ending made no sense at all.",
    "The movie had no emotional resonance.",
    "The characters were poorly developed.",
    "The film was a complete waste of time.",
    "It was an uninspired and dull movie.",
    "The action was boring and predictable.",
    "The movie was just plain bad.",
    "I couldn't stand the film.",
    "The story was incredibly boring.",
    "It was a poorly made film.",
    "I wouldn't watch this again.",
    "The movie was incredibly tedious.",
    "It was a disappointing movie.",
    "I hated every minute of it.",
    "The story was too convoluted to follow.",
    "The film was a major letdown.",
    "It was a boring and uneventful film.",
    "The special effects were awful.",
    "The movie was a total snooze-fest.",
    "I really didn't enjoy this film.",
    "The characters were forgettable.",
    "The movie was overly long and dull.",
    "It was a movie with no direction.",
    "The film had no tension or excitement.",
    "It was an underwhelming film.",
    "The performances were mediocre at best.",
    "I wouldn't recommend this film.",
    "The movie felt like a chore to watch.",
    "It was a complete waste of time.",
    "I didn't like the movie at all.",
    "The film was poorly executed.",
    "It was a boring and uninteresting movie.",
    "I expected much more from this film.",
    "It was a dull and predictable movie.",
    "The acting was terrible.",
    "I hated here.",
    "The movie was meh.",
    "I really did not like it.",
    "This was not good.",
    "It was an unpleasant experience.",
    "That was boring.",
    "I was going to throw out."
]

# Creating the corresponding sentiment labels (1 for positive, 0 for negative)
sentiments = [1] * 100 + [0] * 100

# Create a DataFrame with comments and sentiment
df = pd.DataFrame({
    'Comments': comments,
    'Sentiment': sentiments
})

# Display the first few rows of the DataFrame
df.head()

Comments  Sentiment
0      I loved the movie, the acting was incredible.          1
1     The plot was captivating from start to finish.          1
2                  The cinematography was beautiful.          1
3  The characters were well-developed and interes...          1
4      I was on the edge of my seat the entire time.          1

In [8]:
len(comments)

200

In [17]:
df.tail(10)

Comments  Sentiment
190  I expected much more from this film.          0
191  It was a dull and predictable movie.          0
192              The acting was terrible.          0
193                         I hated here.          0
194                    The movie was meh.          0
195             I really did not like it.          0
196                    This was not good.          0
197      It was an unpleasant experience.          0
198                      That was boring.          0
199             I was going to throw out.          0

In [11]:
import matplotlib.pyplot as plt

In [13]:
import re

In [14]:
import nltk

In [24]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Huawei\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

# Text Cleaning

In [25]:
from nltk.stem.porter import PorterStemmer  
# Importing PorterStemmer to perform stemming 
# (reducing words to their root form)
from nltk.corpus import stopwords           
# Importing stopwords (common words like 'the', 'is', etc.)
import re                                   
# Importing regex module for text preprocessing 

In [26]:
# Initialize an empty list to store the cleaned and processed comments
corpus = [] 

for k in range(0, 200):  
    # Iterate through the first 200 rows of the dataframe
    ps = PorterStemmer()  
    # Create an instance of PorterStemmer to apply stemming on each comment
    
    # Use regular expressions to keep only alphabetic characters 
    comment = re.sub("[^a-zA-Z]", " ", df["Comments"][k])
    
    # Convert the comment to lowercase and split it into individual words
    comment = comment.lower().split()
    
    total_stopwords = stopwords.words("english")
    total_stopwords.remove("not")
    
    # Stemming: apply stemming to each word in the comment not a stopword
    # Stopwords are common words like 'the', 'and', etc.
    comment = [ps.stem(word) for word in comment if not word 
               in set(total_stopwords)]
    
    # Join the stemmed words back together into a single string
    comment = " ".join(comment)
    
    # Append the processed comment to the 'corpus' list
    corpus.append(comment)


In [27]:
print(corpus)

['love movi act incred', 'plot captiv start finish', 'cinematographi beauti', 'charact well develop interest', 'edg seat entir time', 'one best film seen year', 'director fantast job', 'wait watch', 'special effect top notch', 'soundtrack ad much film', 'thrill experi', 'perform amaz', 'outstand piec work', 'stori touch', 'everyth film perfect', 'complet immers world movi', 'action scene breathtak', 'enjoy everi moment', 'humor spot', 'must see movi lover', 'heartwarm stori stay', 'highli recommend film everyon', 'emot rollercoast', 'visual stun masterpiec', 'take eye screen', 'end satisfi', 'film deserv prais get', 'one entertain film year', 'actor deliv stellar perform', 'true cinemat experi', 'script well written engag', 'power film left last impress', 'complet blown away movi', 'emot depth stori amaz', 'film thought provok', 'pace perfect not dull moment', 'director vision execut perfectli', 'visual effect outstand', 'brilliant film highli recommend', 'unforgett experi', 'chemistri

# Bag Creating for Words Model

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 550)

In [34]:
X = cv.fit_transform(corpus).toarray()
X

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
y = df.iloc[:, -1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int64)

In [36]:
len(X[0])

277

In [37]:
len(X[1])

277

# Training the Naive Bayes Model

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, 
                                                    random_state = 0)

In [40]:
from sklearn.naive_bayes import GaussianNB

In [41]:
clf = GaussianNB()

In [42]:
clf.fit(X_train, y_train)

GaussianNB()

In [44]:
y_pred = clf.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), 
                      y_test.reshape(len(y_test), 1)), 1))

[[0 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]]


In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[18  4]
 [ 6 12]]


0.75