In [3]:
# import numpy library
import numpy as np

# Create a numpy array with the values [1, 3, 4, 6, 9]
result = np.array([1,3,4,6,9])
print(result)

[1 3 4 6 9]


In [5]:
# Create an array with values ranging from 2 to 19 with a step of 4 
#(i.e., [2, 6, 10, 14, 18])
rs = np.arange(2,19,4)
print(rs)

[ 2  6 10 14 18]


In [4]:
# Create an array filled with zeros of size 10
rss = np.zeros(10)
print(rss)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# Create an array filled with ones of size 4
re = np.ones(4)
print(re)

[1. 1. 1. 1.]


In [7]:
# Create an array with 4 values linearly spaced between 3 and 14
es = np.linspace(3,14,4)
print(es)

[ 3.          6.66666667 10.33333333 14.        ]


In [8]:
# Generate a random integer between 0 and 10
print(np.random.randint(0,10))

9


In [9]:
# Generate an array of 3 random floats between 0 and 1
print(np.random.rand(3))

[0.67234177 0.16711712 0.20446682]


In [10]:
# Generate an array of 6 random integers between 4 and 18
print(np.random.randint(4,18,6))

[12  4  4  9 11  4]


In [11]:
# Create a numpy array with values from 0 to 49
np_array = np.arange(50)

In [12]:
# Reshape the array into a 5x10 matrix
resultt = np_array.reshape(5,10) # matrix
print(resultt)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [13]:
# Calculate the sum of each row (axis=1 represents rows) 
print(resultt.sum(axis=1)) # sum of rows

[ 45 145 245 345 445]


In [14]:
# Calculate the sum of each column (axis=0 represents columns) and 
print(resultt.sum(axis=0)) # sum of columns

[100 105 110 115 120 125 130 135 140 145]


In [15]:
# Generate an array of 10 random integers between 23 and 100
rndd = np.random.randint(23,100,10)
print(rndd)

[40 63 67 44 26 30 34 69 61 23]


In [16]:
# Find and print the maximum value in the array
maxx = rndd.max()
print("Max value:", maxx)

Max value: 69


In [17]:
# Find and print the minimum value in the array
minn = rndd.min()
print("Min value:", minn)

Min value: 23


In [18]:
# Calculate and print the mean of the array
meann = rndd.mean()
print("Mean value:", meann)

Mean value: 45.7


In [19]:
# Find and print the index of the maximum value in the array
indexofmax = rndd.argmax()
print("Index of max value:", indexofmax)

Index of max value: 7


In [20]:
# Generate an array 'num1' of 6 random integers between 10 and 100
num1 = np.random.randint(10,100,6)
print(num1)

[91 44 51 61 99 70]


In [21]:
# Generate another array 'num2' of 6 random integers between 10 and 100
num2 = np.random.randint(10,100,6)
print(num2)

[98 18 68 50 34 46]


In [22]:
# Add the two arrays element-wise
total = num1 + num2

# Multiply the two arrays element-wise
multi = num1 * num2

# Print both arrays, their sum, and their element-wise product
print(total)
print(multi)

[189  62 119 111 133 116]
[8918  792 3468 3050 3366 3220]


In [23]:
# Calculate the sine of each element in 'num1'
sinn = np.sin(num1)
print(sinn)

[ 0.10598751  0.01770193  0.67022918 -0.96611777 -0.99920683  0.77389068]


In [24]:
# Calculate the cosine of each element in 'num2'
coss = np.cos(num2)
print(coss)

[-0.81928825  0.66031671  0.44014302  0.96496603 -0.84857027 -0.43217794]


In [25]:
# Compute the natural logarithm of each element in 'num1'
log = np.log(num1)
print(log)

[4.51085951 3.78418963 3.93182563 4.11087386 4.59511985 4.24849524]


In [26]:
# Compute the square root of each element in 'num2'
sqr = np.sqrt(num2)
print(sqr)

[9.89949494 4.24264069 8.24621125 7.07106781 5.83095189 6.78232998]


In [27]:
# Reshape 'num1' into a 2x3 matrix
matrix1 = num1.reshape(2,3)

# Reshape 'num2' into a 2x3 matrix
matrix2 = num2.reshape(2,3)

# Print both reshaped matrices
print(matrix1)
print(matrix2)

[[91 44 51]
 [61 99 70]]
[[98 18 68]
 [50 34 46]]


In [28]:
# Vertically stack 'matrix1' and 'matrix2'
vertical_add = np.vstack((matrix1, matrix2))

# Horizontally stack 'matrix1' and 'matrix2'
horizontal_add = np.hstack((matrix1, matrix2))

In [29]:
# Print the vertically and horizontally stacked matrices
print("vertically added:",vertical_add)
print("horizontally added:",horizontal_add)

vertically added: [[91 44 51]
 [61 99 70]
 [98 18 68]
 [50 34 46]]
horizontally added: [[91 44 51 98 18 68]
 [61 99 70 50 34 46]]


In [30]:
# Print the original arrays for reference
print(num1)
print(num2)

[91 44 51 61 99 70]
[98 18 68 50 34 46]


In [31]:
# Check which elements of 'num1' are greater than or equal to 55 (returns a boolean array)
big = num1 >= 55
print(big)

[ True False False  True  True  True]


In [32]:
# Check which elements of 'num2' are even (returns a boolean array)
even = num2 % 2 == 0

# Print the boolean array
print(even)

[ True  True  True  True  True  True]


In [33]:
# Print the elements of 'num2' that are even, using boolean indexing
print(num2[even])

[98 18 68 50 34 46]


In [34]:
print(num1[big])

[91 61 99 70]


In [36]:
# Create a 3x6 matrix including numbers between 0 and 18
array2 = np.arange(18).reshape(3,6)
print(array2)
print('Summation:',sum(array2)) 
# Sum of each column

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
Summation: [18 21 24 27 30 33]


In [44]:
# Set the random seed to ensure reproducibility of the random numbers 
np.random.seed(0)

# Generate a 4x6 matrix of random integers between 20 and 100 (representing marks of 4 students in 6 subjects)
matrix4 = np.random.randint(20, 100, size=(4, 6))

# Print the matrix containing the marks
print(matrix4)

# Find and print the minimum/maximum and total values 
print('Min points in each column:', matrix4.min(axis=0))

print('Max points in each column:', matrix4.max(axis=0))

print('Total points of each row:', matrix4.sum(axis=1))

[[64 67 84 87 87 29]
 [41 56 90 32 78 85]
 [59 66 57 45 97 92]
 [29 40 89 99 67 84]]
Min points in each column: [29 40 57 32 67 29]
Max points in each column: [64 67 90 99 97 92]
Total points of each row: [418 382 416 408]


In [40]:
# Create a 4x4 matrix filled with ones
oness = np.ones((4,4))

# Create a 1D array with a range of values from 0 to 3 (4 values)
addition = np.arange(4)

# Add the 1D array 'addition' to the 4x4 matrix 'oness' (broadcasting will occur)
new = oness + addition

# Print the original 4x4 matrix filled with ones
print(oness)

# Print the 1D array created with arange (0, 1, 2, 3)
print(addition)

# Print a blank line for better formatting
print()

# Print the result of the broadcasting addition
print(new)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3]

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [42]:
# Set a random seed for reproducibility
np.random.seed(0)

# Create a 3x4 matrix of random integers between 0 and 9 (inclusive)
matrx = np.random.randint(15, size=(4, 6))

# Print the original matrix
print('Original matrix:')
print(matrx)

# Print the values of X that are less than 5 (Boolean indexing)
print('Values of matrix less than 5:')
print(matrx[matrx < 5])

Original matrix:
[[12  5  0  3 11  3]
 [ 7  9  3  5  2  4]
 [ 7  6  8  8 12 10]
 [ 1  6  7  7 14  8]]
Values of matrix less than 5:
[0 3 3 3 2 4 1]
